project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides/part1_colab_slides.qmd
    - slides/part2_objects_slides.qmd
    - slides/part3_lists_slides.qmd
    - slides/part4_dictionaries_slides.qmd
    - slides/part5_flow_control_slides.qmd
    - slides/part6_functions_slides.qmd
    - slides/part7_libraries_slides.qmd
    - slides/part8_pandas_intro_slides.qmd
    - slides/part9_pandas_more_slides.qmd
    - slides/part10_visualization_intro_slides.qmd
    - slides/part11_visualization_more_slides.qmd
    - slides/part12_visualization_plotly_slides.qmd
    - slides/part13_simulation_slides.qmd
    - slides/part14_goal_seek_slides.qmd
    - slides/part15_neural_networks_slides.qmd
  resources:
    - CNAME
    - .nojekyll

site:
  title: "Python Workshop"
  site-url: https://workshop.kerryback.com
  feed:
    type: rss2
  description: "introduction to python workshop"
  navbar:
    title: false
    search: true
    left:
      - icon: house-door-fill
        href: https://genai4finance.kerryback.com
        target: _blank

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Kerry Back"

format:
  html:
    code-overflow: wrap
    theme:
      light: flatly
      dark: superhero
      
      
    css: styles.css

execute:
  freeze: auto
