---
title: JGSB PYTHON WORKSHOP
date: September 6, 2025
author: <b>Directed by Kerry Back<br>Rice University<br>[workshop.kerryback.com](https://workshop.kerryback.com)</b>
execute:
  echo: false
  jupyter: python3
  cache: true
format: 
  revealjs:
    highlight-style: github
    code-fold: true
    code-copy: hover
    scrollable: true
    slide-number: true
    preview-links: true
    self-contained: true
    controls: true
    transition: fade
    theme: [league]
    incremental: false
    code-line-numbers: false
---





## What Will you Learn Today? {.incremental}

At the end of this workshop,

- You will <span style="color: #ff6b6b;">not</span> be able to write useful Python programs on your own.

But, you will be able to say:

- I think I remember seeing something like that in the workshop.  I'll <span style="color: #ff6b6b;">ask AI </span> how to do it.  
- Or, I don't know if Python can do that.  But, I'll <span style="color: #ff6b6b;">ask AI </span>anyway.

##

- You will learn where and how to <span style="color: #ff6b6b;">ask AI</span>.
- And, you will be <span style="color: #ff6b6b;">comfortable with the process</span> of 

$$\text{Idea} \; \mapsto \; \text{AI} \; \mapsto \; \text{Python} \; \mapsto \; \text{Result}$$

- So, you will regard this as a go-to tool that you might <span style="color: #ff6b6b;">use every day</span>.

## How Will We Get There?

- 14 self-guided and AI-guided notebooks
- Pause at designated points for everyone to catch up and then discuss

## Start Slow 


- After first 6 notebooks, you won't be able to do anything useful.
- But, you'll understand the <span style="color: #ff6b6b;">basic building blocks</span> of Python.

## Then Speed Up

- Fire hose of code.
- You will see what Python can do.
- Exercises become <span style="color: #ff6b6b;">ask Gemini to ...</span>
- No need to understand or remember every detail.  AI can do it!

## Get Started

- You need a Google account.
- You need to [install Google Drive](https://support.google.com/drive/answer/10838124?hl=en#d4d_install)  
- Drive should appear as a folder on your laptop.  In Windows Explorer, it is under <span style="color: #ff6b6b;"> This PC</span>   
- Create a new folder <span style="color: #ff6b6b;"> This PC - Google Drive - My Drive -Workshop</span>   

## Download and Extract the Zip File

- Download the zip file linked on [workshop.kerryback.com](https://workshop.kerryback.com) to <span style="color: #ff6b6b;"> This PC - Google Drive - My Drive</span>   
- Extract all the files to <span style="color: #ff6b6b;"> This PC - Google Drive - My Drive - Workshop</span>   

## Open Colab

- Go to [https://colab.research.google.com](https://colab.research.google.com)
- You should be looking at an Open Notebook screen
- Choose Google Drive
- Find and open <span style="color: #ff6b6b;"> part1_colab.ipynb</span>   

## Or use the Colab Links

If for any reason you are unable to use Google Drive, use the 'Notebooks in the Zip File' links  at [workshop.kerryback.com](https://workshop.kerryback.com)




